# A composite action that sets up the CI environment for all jobs
name: Set up environment
description: Common setup steps for all jobs
inputs:
  job-name:
    description: Name of the job using this action (for cache differentiation)
    required: false
    default: default
runs:
  using: composite
  steps:
    # Basic setup steps
    - name: Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Configure AWS CLI
      shell: bash
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
        aws configure set default.region us-east-1

    # Restore some of the cached dependencies we generated during the setup job
    - name: Restore Playwright browsers
      uses: actions/cache/restore@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers-
        fail-on-cache-miss: true

    - name: Restore SST providers
      uses: actions/cache/restore@v4
      with:
        path: .sst
        key: ${{ runner.os }}-sst-providers-
        fail-on-cache-miss: true

    # Set up a cache for the turbo results
    - name: Cache Turbo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.job-name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.job-name }}-
          ${{ runner.os }}-turbo-

    # Install dependencies (no --frozen-lockfile due to bun platform detection quirks)
    - name: Install dependencies
      shell: bash
      run: bun install --ignore-scripts

    # Generate some of the types we'll need
    - name: Generate Prisma client
      shell: bash
      run: bun backend db:generate

    - name: Generate docs types
      shell: bash
      run: bun docs postinstall
