/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFRONT_KEY_PAIR_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFRONT_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFRONT_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DAYTONA_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DIRECT_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOOPS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STAGE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "admin": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "apiHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}