/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AXIOM_DATASET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AXIOM_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DIRECT_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LOOPS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STAGE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "apiHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "authHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}