/**
 * Environment variables pulled from Vercel
 * This file is auto-generated by scripts/env/pull-env.ts
 * Do not edit manually - it will be overwritten
 */

declare namespace NodeJS {
  interface ProcessEnv {
    BETTER_AUTH_SECRET: string;
    DATABASE_URL: string;
    DIRECT_DATABASE_URL: string;
    LANGFUSE_PUBLIC_KEY: string;
    LANGFUSE_SECRET_KEY: string;
    LOOPS_API_KEY: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
  }
}
