import { execSync } from 'node:child_process';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// This script is used to pull environment variables from Vercel and generate TypeScript types.

// ---------- HELPERS ----------
/**
 * Pulls environment variables from Vercel and generates TypeScript types.
 * Returns all env vars as an object for programmatic use.
 */
export const pullEnvVars = ({
  env,
  shouldUpdateTypes = false,
}: {
  env: 'production' | 'preview' | 'development';
  shouldUpdateTypes?: boolean;
}): Record<string, string> => {
  const currentFileDir = dirname(fileURLToPath(import.meta.url));
  const backendDir = resolve(currentFileDir, '../..');
  const envPath = join(backendDir, '.env');
  const envDtsPath = join(backendDir, 'env.d.ts');

  console.log(`Pulling environment variables from Vercel (${env})...`);

  try {
    // Pull env vars from Vercel (creates/updates .env file)
    execSync(`vercel env pull .env --yes --environment=${env}`, {
      stdio: 'ignore',
      cwd: backendDir,
    });
  } catch (error) {
    console.error('❌ Failed to pull environment variables from Vercel');
    throw error;
  }

  // Check if .env file was created
  if (!existsSync(envPath)) {
    console.warn('❌ No .env file found after pulling from Vercel');
    return {};
  }

  // Parse .env file
  const envContent = readFileSync(envPath, 'utf8');
  const envVars: Record<string, string> = {};

  // Parse .env format: KEY=VALUE or KEY="VALUE" or KEY='VALUE'
  const envRegex =
    /^([A-Z_][A-Z0-9_]*)\s*=\s*(?:(?:"([^"]*)")|(?:'([^']*)')|([^\s#]*))$/gm;
  let match: RegExpExecArray | null = envRegex.exec(envContent);

  while (match !== null) {
    const key = match[1];
    if (key) {
      // Value can be in double quotes, single quotes, or unquoted
      const value = match[2] ?? match[3] ?? match[4] ?? '';
      envVars[key] = value;
    }
    match = envRegex.exec(envContent);
  }

  // Generate and write TypeScript type definitions if requested
  if (shouldUpdateTypes) {
    const typeDefinitions = generateTypeDefinitions(envVars);
    writeFileSync(envDtsPath, typeDefinitions, 'utf8');
  }

  // Delete the .env file (we only need the types, not the file itself)
  // This prevents outdated environment variables from silently overriding current values (auto-loaded during vercel dev)
  unlinkSync(envPath);

  console.log('✔ Environment variables pulled successfully\n');

  return envVars;
};

/**
 * Generates TypeScript type definitions for environment variables
 */
const generateTypeDefinitions = (envVars: Record<string, string>): string => {
  const keys = Object.keys(envVars)
    .filter((key) => key !== 'VERCEL_OIDC_TOKEN') // Ignore VERCEL_OIDC_TOKEN
    .sort();
  const interfaceProperties = keys
    .map((key) => `    ${key}: string;`)
    .join('\n');

  return `/**
 * Environment variables pulled from Vercel
 * This file is auto-generated by scripts/env/pull-env.ts
 * Do not edit manually - it will be overwritten
 */

declare namespace NodeJS {
  interface ProcessEnv {
${interfaceProperties}
  }
}
`;
};

// ---------- DIRECT INVOCATION ----------
// If we are running the script directly, we should run the logic below (this check avoids running it on simple imports)
const currentFile = fileURLToPath(import.meta.url).replace(/\.ts$/, '');
const executedFile = process.argv[1].replace(/\.ts$/, '');
if (currentFile === executedFile) {
  try {
    // CI invocation - update types
    pullEnvVars({ env: 'development', shouldUpdateTypes: true });
    process.exit(0);
  } catch (error: unknown) {
    console.error('Error pulling environment variables:', error);
    process.exit(1);
  }
}
