import { SeverityNumber } from '@opentelemetry/api-logs';
import { OTLPLogExporter } from '@opentelemetry/exporter-logs-otlp-http';
import { resourceFromAttributes } from '@opentelemetry/resources';
import { BatchLogRecordProcessor, LoggerProvider } from '@opentelemetry/sdk-logs';
import { config } from '@repo/config';
import pino from 'pino';
import {
  GlobalContextStorageProvider,
  lambdaRequestTracker,
  pinoLambdaDestination,
} from 'pino-lambda';
import pretty from 'pino-pretty';

// ---------- OTEL LOGGER ----------
/** Map pino level labels to OTel severity */
const pinoLevelToSeverity: Record<string, SeverityNumber> = {
  trace: SeverityNumber.TRACE,
  debug: SeverityNumber.DEBUG,
  info: SeverityNumber.INFO,
  warn: SeverityNumber.WARN,
  error: SeverityNumber.ERROR,
  fatal: SeverityNumber.FATAL,
};

/** Initialize the OTel logger provider for PostHog when running in AWS */
const { otelLogger, otelProvider } = (() => {
  // We only ship logs to PostHog if it's enabled (usually in deployed AWS environment)
  if (!config.posthog.isEnabled || !config.posthog.apiKey) {
    return { otelLogger: undefined, otelProvider: undefined };
  }

  // Create the exporter for PostHog
  const exporter = new OTLPLogExporter({
    url: 'https://us.i.posthog.com/i/v1/logs',
    headers: {
      Authorization: `Bearer ${config.posthog.apiKey}`,
    },
  });

  // Create the provider for the OTel logger
  const provider = new LoggerProvider({
    resource: resourceFromAttributes({
      'service.name': 'backend',
      env: config.stage,
    }),
    processors: [new BatchLogRecordProcessor(exporter)],
  });

  return { otelLogger: provider.getLogger('pino'), otelProvider: provider };
})();

// ---------- OTHER DESTINATIONS ----------
/** Our lambda destination (ensures things are formatted for cloudwatch) */
const lambdaDest = pinoLambdaDestination();
/** Our pretty destination (ensures things are formatted for the console) */
const prettyDest = pretty({
  colorize: true,
  translateTime: 'SYS:HH:mm:ss',
  // Ignore some params that we don't care about locally
  ignore:
    'userId,organizationId,sessionId,request,langfuseTraceId,awsRequestId,apiRequestId,x-correlation-id,x-correlation-trace-id',
});

// ---------- HELPERS ----------
/** Adds lambda request context to the current request context */
export const addLambdaRequestContext = lambdaRequestTracker();

type LogMetadata = {
  langfuseTraceId?: string;
  userId?: string;
  awsRequestId?: string;
  sessionId?: string;
  request?: { method?: string; path?: string };
};

/** Gets the current request context */
export const getLogMetadata = () =>
  ({ ...GlobalContextStorageProvider.getContext() }) as LogMetadata;

/** Adds metadata to the current request context */
export const addLogMetadata = (metadata: Record<string, unknown>) => {
  GlobalContextStorageProvider.updateContext(metadata);
};

/** Ensures all logs are flushed */
export const flushLogs = async () => {
  try {
    if (otelProvider) {
      await otelProvider.forceFlush();
    }
  } catch (error) {
    console.error('[log] Failed to flush logs:', error);
  }
};

/** The message format generated by pino */
type PinoLog = {
  level: string;
  msg: string;
  [key: string]: unknown;
};

// ---------- PINO ----------
/** Create a custom destination that handles all our destinations */
const customDestination = {
  write: (payload: string) => {
    try {
      // When we're running in AWS, structure the base logs for cloudwatch
      if (config.isAWS) {
        lambdaDest.write(payload);
      }
      // If we're running locally, show the pretty output
      else {
        prettyDest.write(payload);
      }

        // Ship logs to PostHog via OpenTelemetry if it's enabled
        if (config.posthog.isEnabled && otelLogger) {
          const {
            time,
            level,
            msg,
            'x-correlation-id': correlationId,
            'x-correlation-trace-id': traceId,
            ...context
          } = JSON.parse(payload) as PinoLog;

          otelLogger.emit({
            severityNumber: pinoLevelToSeverity[level] ?? SeverityNumber.INFO,
            severityText: level,
            body: msg,
            timestamp: time ? new Date(time as string | number) : undefined,
            attributes: {
              ...context,
              // PostHog session replay linking
              ...(context.sessionId ? { sessionId: context.sessionId as string } : {}),
              ...(context.userId ? { posthogDistinctId: context.userId as string } : {}),
              // Correlation IDs
              ...(correlationId ? { 'x-correlation-id': correlationId as string } : {}),
              ...(traceId ? { 'x-correlation-trace-id': traceId as string } : {}),
            },
          });
        }

    } catch (error) {
      console.error('[log] Failed to handle log:', error);
    }
  },
};

// Create our logging instance
export const log = pino(
  {
    level: process.env.LOG_LEVEL || 'info',
    formatters: {
      level: (label) => ({ level: label }),
    },
    // Add any additional global context into our logs
    mixin: () => getLogMetadata(),
  },
  customDestination,
);
